src/Entity/Recipe.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RecipeRepository")
 */
class Recipe
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_created;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_updated;

    /**
     * @ORM\Column(type="text")
     */
    private $instruction;

    /**
     * @ORM\Column(type="integer")
     */
    private $number_people;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ingredient", mappedBy="recipe", cascade={"persist"})
     */
    private $ingredients;

    public function __construct()
    {
        $this->ingredients = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDateCreated(): ?\DateTimeInterface
    {
        return $this->date_created;
    }

    public function setDateCreated(\DateTimeInterface $date_created): self
    {
        $this->date_created = $date_created;

        return $this;
    }

    public function getDateUpdated(): ?\DateTimeInterface
    {
        return $this->date_updated;
    }

    public function setDateUpdated(\DateTimeInterface $date_updated): self
    {
        $this->date_updated = $date_updated;

        return $this;
    }

    public function getInstruction(): ?string
    {
        return $this->instruction;
    }

    public function setInstruction(string $instruction): self
    {
        $this->instruction = $instruction;

        return $this;
    }

    public function getNumberPeople(): ?int
    {
        return $this->number_people;
    }

    public function setNumberPeople(int $number_people): self
    {
        $this->number_people = $number_people;

        return $this;
    }

    /**
     * @return Collection|Ingredient[]
     */
    public function getIngredients(): Collection
    {
        return $this->ingredients;
    }

    public function addIngredient(Ingredient $ingredient): self
    {
        if (!$this->ingredients->contains($ingredient)) {
            $this->ingredients[] = $ingredient;
            $ingredient->setRecipe($this);
        }

        return $this;
    }

    public function removeIngredient(Ingredient $ingredient): self
    {
        if ($this->ingredients->contains($ingredient)) {
            $this->ingredients->removeElement($ingredient);
            // set the owning side to null (unless already changed)
            if ($ingredient->getRecipe() === $this) {
                $ingredient->setRecipe(null);
            }
        }

        return $this;
    }
}

src/Form/RecipeType.php
<?php

namespace App\Form;

use App\Entity\Recipe;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RecipeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('instruction')
            ->add('number_people')
            ->add('ingredients', CollectionType::class, [
                'entry_type' => IngredientType::class,
                'entry_options' => ['label' => true],
                'allow_add' => true,
                'allow_delete' => true
            ])
            ->add('save', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Recipe::class,
        ]);
    }
}

src/Controller/RecipeController.php
<?php

namespace App\Controller;

use App\Entity\Recipe;
use App\Form\RecipeType;
use App\Repository\RecipeRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class RecipeController extends AbstractController
{
    /**
     * @Route("/recipes", name="recipe_list")
     * @param RecipeRepository $recipeRepository
     * @return Response
     */
    public function list(RecipeRepository $recipeRepository)
    {
        $recipes = $recipeRepository->findAll();
        return $this->render('recipe/recipes.html.twig', [
            'recipes' => $recipes
        ]);
    }

    /**
     * @Route("/recipe/{id}", name="recipe_show", requirements={"id"="\d+"})
     * @param Recipe $recipe
     * @return Response
     */
    public function show(Recipe $recipe)
    {
        return $this->render('recipe/recipe.html.twig', [
            'recipe' => $recipe
        ]);
    }

    /**
     * @Route("/recipe/create", name="recipe_create")
     * @param Request $request
     * @return RedirectResponse|Response
     * @throws Exception
     */
    public function create(Request $request)
    {
        $form = $this->createForm(RecipeType::class);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $recipe = $form->getData();

            $datetime = new DateTime();
            $recipe->setDateCreated($datetime);
            $recipe->setDateUpdated($datetime);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($recipe);
            $entityManager->flush();

            return $this->redirectToRoute('recipe_show', ['id' => $recipe->getId()]);
        }

        return $this->render('recipe/form.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/recipe/{id}/edit", name="recipe_edit")
     * @param Recipe $recipe
     * @param Request $request
     * @return RedirectResponse|Response
     * @throws Exception
     */
    public function edit(Recipe $recipe, Request $request)
    {
        // Create an ArrayCollection of the current Ingredient objects in the database
        $originalIngredients = new ArrayCollection();
        foreach ($recipe->getIngredients() as $ingredient) {
            $originalIngredients->add($ingredient);
        }

        $form = $this->createForm(RecipeType::class, $recipe);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            /** @var Recipe $recipe */
            $recipe = $form->getData();

            $datetime = new DateTime();
            $recipe->setDateUpdated($datetime);

            $entityManager = $this->getDoctrine()->getManager();
            foreach ($originalIngredients as $ingredient) {
                if (!$recipe->getIngredients()->contains($ingredient)) {
                    $ingredient->getRecipe()->removeIngredient($ingredient);
                    $entityManager->remove($ingredient);
                }
            }
            foreach($recipe->getIngredients() as $ingredient) {
                $ingredient->setRecipe($recipe);
            }

            $entityManager->persist($recipe);
            $entityManager->flush();

            return $this->redirectToRoute('recipe_show', ['id' => $recipe->getId()]);
        }

        return $this->render('recipe/form.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/recipe/{id}/delete", name="recipe_delete")
     * @param Recipe $recipe
     * @return RedirectResponse
     */
    public function delete(Recipe $recipe)
    {
        $entityManager = $this->getDoctrine()->getManager();
        foreach ($recipe->getIngredients() as $ingredient) {
            $ingredient->getRecipe()->removeIngredient($ingredient);
            $entityManager->remove($ingredient);
        }
        $entityManager->remove($recipe);
        $entityManager->flush();

        return $this->redirectToRoute('recipe_list');
    }
}

templates/recipe/form.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello RecipeController!{% endblock %}

{% block body %}
    <div class="container mt-5">
        <h1>Création d'une recette</h1>

        {{ form_start(form) }}

        {{ form_row(form.name) }}
        {{ form_row(form.instruction) }}
        {{ form_row(form.number_people) }}

        {{ form_label(form.ingredients) }}
        <ul class="list-group ingredients" data-prototype="{{ form_widget(form.ingredients.vars.prototype)|e('html_attr') }}">
            {% if form.ingredients is not empty %}
                {% for ingredient in form.ingredients %}
                    <li class="list-group-item">
                        {{ form_widget(ingredient) }}
                        <a href="#" class="remove-ingredient text-danger">Retirer l'ingrédient</a>
                    </li>
                {% endfor %}
            {% else %}
                {{ form_widget(form.ingredients) }}
            {% endif %}
        </ul>

        <div class="mt-3">
            {{ form_row(form.save) }}
        </div>

        {{ form_end(form) }}
    </div>

    <script>

    </script>
{% endblock %}

 {% block javascripts %}
     {{ parent() }}
     {{ encore_entry_script_tags('recipe_form') }}
 {% endblock %}

templates/recipe/recipe.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello RecipeController!{% endblock %}

{% block body %}
    <div class="container mt-5">
        <div class="row">
            <div class="col">
            <h1>
                {{ recipe.name }}
                <small class="text-muted"> - {{ recipe.numberPeople }} personne{% if recipe.numberPeople > 1 %}s{% endif %}</small>
            </h1>
            </div>
            <div class="col">
                <h2>Ingrédients</h2>
                <ul class="list-group">
                    {% for ingredient in recipe.ingredients %}
                    <li class="list-group-item">
                        {{ ingredient.food.name }}  <span class="float-right">{{ ingredient.quantity }}</span>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <div class="jumbotron jumbotron-fluid mt-3">
            <div class="container">
                <h1 class="display-4">Instructions</h1>
                <p class="lead">{{ recipe.instruction }}</p>
            </div>
        </div>

        <div class="btn-group" role="group" aria-label="Actions">
            <a href="{{ path('recipe_edit', {id: recipe.id}) }}" class="btn btn-secondary">Modifier</a>
            <a href="{{ path('recipe_delete', {id: recipe.id}) }}" class="btn btn-danger">Supprimer</a>
        </div>
    </div>
{% endblock %}

templates/recipe/recipes.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello RecipeController!{% endblock %}

{% block body %}
    <div class="container mt-5">
        <div class="row">
            <div class="col">
                <h1 class="m-0">Liste des recettes</h1>
            </div>
            <div class="col text-right align-self-end">
                <a href="{{ path('recipe_create') }}" class="btn btn-primary">Créer une recette</a>
            </div>
        </div>
        {% if recipes is not empty %}
        <table class="table table-hover mt-3">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Recette</th>
                <th scope="col">Nombre de personnes</th>
                <th scope="col">Date de création</th>
                <th scope="col">Dernière mise à jour</th>
                <th scope="col">Action</th>
            </tr>
            </thead>
            <tbody>
            {% for recipe in recipes %}
            <tr>
                <th scope="row">{{ recipe.id }}</th>
                <td>{{ recipe.name }}</td>
                <td>{{ recipe.numberPeople }}</td>
                <td>{{ recipe.dateCreated|date("d/m/Y") }}</td>
                <td>{{ recipe.dateUpdated|date("d/m/Y") }}</td>
                <td>
                    <a href="{{ path('recipe_show', {id: recipe.id}) }}">Voir</a> -
                    <a href="{{ path('recipe_edit', {id: recipe.id}) }}">Modifier</a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
{% endblock %}